#+PROPERTY: header-args:bash :tangle genomes.sh

#+begin_src bash :tangle genomes.sh

ts="Enterobacter cloacae subsp. cloacae ATCC 13047"
usage="$(basename $0) [-h] -t <typeStrain> -d <downloadDir>"
usage="$usage -n <neighborsDb>
Download target and neighbor genomes for a type strain.
Example: bash genomes.sh -t \"$ts\""
usage="$usage -d ecl -n neidb"

while getopts "ht:d:n:" arg; do
    case $arg in
	h) echo "$usage"
	   exit;;
	t) strain=$OPTARG;;
	d) dir=$OPTARG;;
	n) db=$OPTARG;;
	\?) exit 1;;
    esac
done       
#+end_src

yine optarg ile degiskenleri duzenledik ve farkli bir sey yazdiysa
exit 1 deyip programi durdurduk

#+begin_src bash :tangle genomes.sh
if [[ ! $strain ]]; then
   echo "Please provide a type strain"
   echo "$usage"
   exit 1
fi
if [[ ! $dir ]]; then
    echo "Please provide a download directory."
    echo "$usage"
    exit 1
else
    if [[ -d $dir ]]; then
	echo "Download directory already exists."
	exit 1
    fi
fi      
#+end_src

#eger download directory varsa yeni olusturmasini istiyoruz

#+begin_src bash :tangle genomes.sh
if [[ ! $db ]]; then
    echo "Please provide a Neighbors database."
    echo "$usage"
    exit 1
else
    if [[ ! -f $db ]]; then
	echo "Database $db doesn't exist."
	exit 1
    fi
fi
#+end_src

taxonomic idyi burda buluyoruz

#+begin_src bash :tangle genomes.sh
mkdir $dir
cd $dir
db="../$db"
tid=$(taxi "$strain" $db | 
	  tail -n +2 |
	  awk '{print $2}')
echo $tid |
    neighbors -l $db > acc.txt
for a in t n; do
    grep ^${a} acc.txt |
	awk '{print $2}' > ${a}acc.txt
done
for a in t n; do  
    datasets download genome accession \
	     --inputfile ${a}acc.txt \
	     --assembly-level complete,chromosome \
	     --exclude-atypical \
	     --dehydrated \
	     --filename ${a}data.zip
done

#+end_src


-s flagi dosya var mi ve boyutu sifirdan buyuk mu diye kontrol ediyor. dosya varsa ve bos degilse true doner

tdata/
├── ncbi_dataset

gercek genom dosyalarini indirir
eger sadece target varsa ve nb yoksa targetlar da silinir

#+begin_src bash :tangle genomes.sh
for a in t n; do
    if [[ -s ${a}data.zip ]]; then    
	unzip ${a}data.zip -d ${a}data       
	datasets rehydrate --directory ${a}data      
    else
	if [[ -s tdata.zip ]]; then
	    rm -r tdata*
	fi
	exit   
    fi
done
#+end_src


burda karmasik klasor yapisini tek bir directoryde topladik

#+begin_src bash :tangle genomes.sh
mkdir all
for p in t n; do
    for a in ${p}data/ncbi_dataset/data/*/*.fna; do
	b=$(basename $a)
	mv $a all/${p}$b
    done
done 
#+end_src



all.phyl icin nan var mi? varsa hata verme (-p) ve rejected directorysini olustur
problematic genomlari tek tek cikariyoruz
butun nanlari cikarip elde ettigimiz yeni dosyaya nj yapiyoruz

#+begin_src bash :tangle genomes.sh
n=$(ls all/ | wc -l)
if [[ $n -le 1 ]]; then   
    echo "Need at least two genomes to calculate phylogeny."
    exit 1
elif [[ $n -eq 2 ]]; then
    phylonium all/* |
	upgma
	land > all.nwk
else
    pyhlonium all/* 2>/dev/null > all.phyl

    while grep -qw "nan" all.phyl  
    do
	mkdir -p Rejected      
	    name=$(awk '{count=0; for(i=2; i<=NF;i++){if($i =="nan") count++}}{print $1, count}' all.phyl |
                        sort -n -k2,2 -r |        
                        head -n 1  |
                        awk '{print $1}')
             
            mv all/$name Rejected/
            phylonium all/* 2>/dev/null > all.phyl
    done
    nj all.phyl |       
	midRoot |
	lan > all.nwk
fi

#+end_src

#+begin_src bash :tangle genomes.sh
tc=$(fintac all.nwk |
	 tail -n +2 |
	 sort -k 6 -n -r |
	 head -n 1 |
	 awk '{print $1}')
mkdir targets
#+end_src

tc sadece rakamlardan olusan bir degiskense true dondurur.
bu durumda target clade bir node demektir ve altinda birden fazla genom bulunur.
yani eger sayi 17ysi sunu yapar: 17 numaralı clade içindeki tüm taksonları listele
sonra hepsi bir directoryde bagli olarak listelenir

#+begin_src bash :tangle genomes.sh
if [[ $tc =~ ^[0-9]+$ ]]; then      
    pickle $tc all.nwk |
	grep -v '^#' |         
	while read a; do
	    ln -s $(pwd)/all/$a $(pwd)/targets/$a
	done                      
else
    pickle $tc all.nwk |
	awk 'NR==2{print $2}' |
	while read a; do
	    ln -s $(pwd)/all/$a $(pwd)/targets/$a
	done
fi
#+end_src


#+begin_src bash :tangle genomes.sh
mkdir neighbors
pickle -c $tc all.nwk |
    grep -v '^#' |
    while read a; do
	ln -s $(pwd)/all/$a $(pwd)/neighbors/$a
    done
#+end_src
